###########################################################
# GCC template makefile
###########################################################

DEFAULT_ASMSOURCES = startup_stm32f10x_md.s

ASM_SOURCES += $(DEFAULT_ASMSOURCES)