###########################################################
# GCC template makefile
###########################################################

FREERTOS_HEAP_SOURCES = 
FREERTOS_HEAP_SOURCES += heap_2.c

C_SOURCES += $(FREERTOS_HEAP_SOURCES)