###########################################################
# GCC template makefile
###########################################################


CORE_SOURCS = 
CORE_SOURCS += core_cm3.c
CORE_SOURCS += system_stm32f10x.c




C_SOURCES += $(CORE_SOURCS)