###########################################################
# GCC template makefile
###########################################################

MAIN_SOURCE = 
MAIN_SOURCE += Main.c

C_SOURCES += $(MAIN_SOURCE)