###########################################################
# GCC template makefile
###########################################################

MENU_SOURCES =
MENU_SOURCES += 
MENU_SOURCES += 



C_SOURCES += $(MENU_SOURCES)