###########################################################
# GCC template makefile
###########################################################

#FREERTOS_MIN_SOURCES = 
#FREERTOS_MIN_SOURCES += AbortDelay.c
#FREERTOS_MIN_SOURCES += BlockQ.c
#FREERTOS_MIN_SOURCES += blocktim.c
#FREERTOS_MIN_SOURCES += comtest_strings.c
#FREERTOS_MIN_SOURCES += comtest.c
#FREERTOS_MIN_SOURCES += countsem.c
#FREERTOS_MIN_SOURCES += crflash.c
#FREERTOS_MIN_SOURCES += crhook.c
#FREERTOS_MIN_SOURCES += death.c
#FREERTOS_MIN_SOURCES += dynamic.c
#FREERTOS_MIN_SOURCES += EventGroupsDemo.c
#FREERTOS_MIN_SOURCES += flash_timer.c
#FREERTOS_MIN_SOURCES += flash.c
#FREERTOS_MIN_SOURCES += flop.c
#FREERTOS_MIN_SOURCES += GenQTest.c
#FREERTOS_MIN_SOURCES += ineger.c
#FREERTOS_MIN_SOURCES += IntQueue.c
#FREERTOS_MIN_SOURCES += IntSemTest.c
#FREERTOS_MIN_SOURCES += MessageBufferAMP.c
#FREERTOS_MIN_SOURCES += MessageBufferDemo.c

C_SOURCES += $(FREERTOS_MIN_SOURCES)