###########################################################
# GCC template makefile
###########################################################

FREERTOS_PORTABLE_SOURCES = 
FREERTOS_PORTABLE_SOURCES += port.c

C_SOURCES += $(FREERTOS_PORTABLE_SOURCES)